### ISSUE TITLE
Extract dl1 crashes if monitor file is empty

### ISSUE THREAD

**Issue by RichardWhite109** [cta-chec/CHECLabPy#27]
extract_dl1 should deal with an empty monitor file (or a file that contains no matching events). Suggest to print a warning (perhaps via catching this exception - or before it occurs, but should not crash) and then don't add the monitor data frame to the output

```
Creating HDF5 file: /d2/checs_tests/test/Run17438_dl1.h5
WARNING MonitorWriter assumes monitor timestamps are in MPIK time. This needs fixing once they have been converted to unix/UTC
Reading monitor information from: /d2/checs_tests/test/Run17438.mon
Traceback (most recent call last):
  File "/home/cta/Software/CHECLabPy/CHECLabPy/core/io.py", line 282, in __init__
    self.monitor_ev = next(self.monitor_it)
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/cta/Software/CHECLabPy/scripts/extract_dl1.py", line 131, in <module>
    main()
  File "/home/cta/Software/CHECLabPy/scripts/extract_dl1.py", line 72, in main
    with DL1Writer(output_path, n_events*n_pixels, args.monitor) as writer:
  File "/home/cta/Software/CHECLabPy/CHECLabPy/core/io.py", line 159, in __init__
    self.monitor = MonitorWriter(monitor_path, self)
  File "/home/cta/Software/CHECLabPy/CHECLabPy/core/io.py", line 284, in __init__
    raise IOError("No monitor events found")
OSError: No monitor events found
```

**Comment by watsonjj** [comment]
Fixed in #31
