### ISSUE TITLE
Crash on empty / mis-matching monitor event file

### ISSUE THREAD

**Issue by RichardWhite109** [cta-chec/CHECLabPy#40]
The following command fails: 

`python /home/cta/Software/CHECLabPy/scripts/extract_dl1.py -f /d2/checs_tests/test//Run36580_r1ntf.tio -r CrossCorrelation -m/d2/checs_tests/test//Run36580.mon`

with the following output

`WARNING: events are >5 minutes before start of monitor file, are you sure it is the correct monitor file?
Processing events: 100%|| 1234/1234 [01:00<00:00, 20.41it/s]
Traceback (most recent call last):
  File "/home/cta/Software/CHECLabPy/scripts/extract_dl1.py", line 132, in <module>
    main()
  File "/home/cta/Software/CHECLabPy/scripts/extract_dl1.py", line 128, in main
    writer.add_mapping(mapping)
  File "/home/cta/Software/CHECLabPy/CHECLabPy/core/io.py", line 190, in __exit__
    self.finish()
  File "/home/cta/Software/CHECLabPy/CHECLabPy/core/io.py", line 257, in finish
    self.monitor.finish()
  File "/home/cta/Software/CHECLabPy/CHECLabPy/core/io.py", line 438, in finish
    for _ in self.monitor_it:
  File "/home/cta/Software/CHECLabPy/CHECLabPy/core/io.py", line 327, in _get_next_monitor_event
    "{} {}".format(data[0], data[1]),
IndexError: list index out of range
Closing remaining open files:/d2/checs_tests/test//Run36580_dl1.h5...done`

Suspect that when there are no matching monitor events found then this occurs? So could maybe just deal with an empty monitor event list in a nicer way? e.g. "WARNING no monitor events matching, no monitor data will be added to the output"?

**Comment by watsonjj** [comment]
No, this was an error as it didn't properly handle when a line was "\n"

**Comment by watsonjj** [comment]
Fixed in #41
